# Site settings
title: Milestone 1
tag_text: Milestone 1
description: The milestone 1 website for the final project of the 190
url: "http://127.0.0.1:4000"

# Build settings
markdown: kramdown

exclude: ["README.md"]
